name: Dynamic Badges Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  dynamic_badges_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.7.0
